apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: zg2tgt4di-python
  janus-idp.io/tekton: zg2tgt4di-python
  backstage.io/kubernetes-id: zg2tgt4di-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: zg2tgt4di-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
